image: 'atlassian/default-image:2'
pipelines:
  branches:
    dev:
      - step:
          name: Update Development Stage CodeCommit Repo
          deployment: Development
          script:
            - chmod +x bitbucket-push-to-codecommit.sh  # Make bitbucket-push-to-codecommit.sh executable
            - ./bitbucket-push-to-codecommit.sh  # Execute bitbucket-push-to-codecommit.sh script
    prd:
      - step:
          name: Update Production Stage CodeCommit Repo
          deployment: Production
          script:
            - chmod +x bitbucket-push-to-codecommit.sh  # Make bitbucket-push-to-codecommit.sh executable
            - ./bitbucket-push-to-codecommit.sh  # Execute bitbucket-push-to-codecommit.sh script