# This is a basic workflow to help you get started with Actions

name: CodeCommitReplication

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev", "prd" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  environment_check:
    runs-on: ubuntu-latest
    steps:    
      - name: Set environment based on branch
        id: branch_check
        run: |
          echo "Running on branch ${{ github.ref }}"
          if [ "${{ github.ref }}" = "refs/heads/prd" ]; then
            echo "env_name=Production"  >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" = "refs/heads/dev" ]; then
            echo "env_name=Development" >> $GITHUB_OUTPUT
          fi
      
      - name: Display environment check
        run: echo "Using ${{ steps.branch_check.outputs.env_name }} for branch ${{ github.ref }}"

    outputs:
      env_name: ${{ steps.branch_check.outputs.env_name }}

  code_replication:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [environment_check]
    environment:
      name: ${{ needs.environment_check.outputs.env_name }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          pwd
          ls
          # echo "Host ${{ secrets.CODECOMMIT_HOST }}" >> ~/.ssh/config
          # echo "User ${{ secrets.SSH_KEY_ID }}" >> ~/.ssh/config
          git remote add codecommit ${{ secrets.CODECOMMIT_REPO }}
          git push -u codecommit ${{ secrets.BRANCH_NAME }}
